apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cs3219-db
  namespace: cs3219
spec:
  serviceName: "cs3219-db"
  replicas: 1
  selector:
    matchLabels:
      app: cs3219-db
  template:
    metadata:
      labels:
        app: cs3219-db
    spec:
      containers:
      - name: cs3219-db
        image: cs3219/mariadb:1.0.0
        imagePullPolicy: Never
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: password
        - name: MARIADB_DATABASE
          value: cs3219
        ports:
        - containerPort: 3306
          name: cs3219-db
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
